const Constcounty = [
  { country: 'Mongolia', code: 'MN', dial_code: '+976', flag: '🇲🇳' },
  { country: 'Afghanistan', code: 'AF', dial_code: '+93', flag: '🇦🇫' },
  { country: 'Albania', code: 'AL', dial_code: '+355', flag: '🇦🇱' },
  { country: 'Algeria', code: 'DZ', dial_code: '+213', flag: '🇩🇿' },
  { country: 'Andorra', code: 'AD', dial_code: '+376', flag: '🇦🇩' },
  { country: 'Angola', code: 'AO', dial_code: '+244', flag: '🇦🇴' },
  { country: 'Argentina', code: 'AR', dial_code: '+54', flag: '🇦🇷' },
  { country: 'Armenia', code: 'AM', dial_code: '+374', flag: '🇦🇲' },
  { country: 'Australia', code: 'AU', dial_code: '+61', flag: '🇦🇺' },
  { country: 'Austria', code: 'AT', dial_code: '+43', flag: '🇦🇹' },
  { country: 'Azerbaijan', code: 'AZ', dial_code: '+994', flag: '🇦🇿' },
  { country: 'Bahrain', code: 'BH', dial_code: '+973', flag: '🇧🇭' },
  { country: 'Bangladesh', code: 'BD', dial_code: '+880', flag: '🇧🇩' },
  { country: 'Belgium', code: 'BE', dial_code: '+32', flag: '🇧🇪' },
  { country: 'Bhutan', code: 'BT', dial_code: '+975', flag: '🇧🇹' },
  { country: 'Brazil', code: 'BR', dial_code: '+55', flag: '🇧🇷' },
  { country: 'Bulgaria', code: 'BG', dial_code: '+359', flag: '🇧🇬' },
  { country: 'Cambodia', code: 'KH', dial_code: '+855', flag: '🇰🇭' },
  { country: 'Canada', code: 'CA', dial_code: '+1', flag: '🇨🇦' },
  { country: 'China', code: 'CN', dial_code: '+86', flag: '🇨🇳' },
  { country: 'Colombia', code: 'CO', dial_code: '+57', flag: '🇨🇴' },
  { country: 'Denmark', code: 'DK', dial_code: '+45', flag: '🇩🇰' },
  { country: 'Egypt', code: 'EG', dial_code: '+20', flag: '🇪🇬' },
  { country: 'Finland', code: 'FI', dial_code: '+358', flag: '🇫🇮' },
  { country: 'France', code: 'FR', dial_code: '+33', flag: '🇫🇷' },
  { country: 'Germany', code: 'DE', dial_code: '+49', flag: '🇩🇪' },
  { country: 'Hong Kong', code: 'HK', dial_code: '+852', flag: '🇭🇰' },
  { country: 'India', code: 'IN', dial_code: '+91', flag: '🇮🇳' },
  { country: 'Indonesia', code: 'ID', dial_code: '+62', flag: '🇮🇩' },
  { country: 'Iran', code: 'IR', dial_code: '+98', flag: '🇮🇷' },
  { country: 'Iraq', code: 'IQ', dial_code: '+964', flag: '🇮🇶' },
  { country: 'Ireland', code: 'IE', dial_code: '+353', flag: '🇮🇪' },
  { country: 'Israel', code: 'IL', dial_code: '+972', flag: '🇮🇱' },
  { country: 'Italy', code: 'IT', dial_code: '+39', flag: '🇮🇹' },
  { country: 'Japan', code: 'JP', dial_code: '+81', flag: '🇯🇵' },
  { country: 'Jordan', code: 'JO', dial_code: '+962', flag: '🇯🇴' },
  { country: 'Kenya', code: 'KE', dial_code: '+254', flag: '🇰🇪' },
  { country: 'Kuwait', code: 'KW', dial_code: '+965', flag: '🇰🇼' },
  { country: 'Malaysia', code: 'MY', dial_code: '+60', flag: '🇲🇾' },
  { country: 'Maldives', code: 'MV', dial_code: '+960', flag: '🇲🇻' },
  { country: 'Mexico', code: 'MX', dial_code: '+52', flag: '🇲🇽' },
  { country: 'Nepal', code: 'NP', dial_code: '+977', flag: '🇳🇵' },
  { country: 'Netherlands', code: 'NL', dial_code: '+31', flag: '🇳🇱' },
  { country: 'New Zealand', code: 'NZ', dial_code: '+64', flag: '🇳🇿' },
  { country: 'Nigeria', code: 'NG', dial_code: '+234', flag: '🇳🇬' },
  { country: 'Norway', code: 'NO', dial_code: '+47', flag: '🇳🇴' },
  { country: 'Oman', code: 'OM', dial_code: '+968', flag: '🇴🇲' },
  { country: 'Pakistan', code: 'PK', dial_code: '+92', flag: '🇵🇰' },
  { country: 'Philippines', code: 'PH', dial_code: '+63', flag: '🇵🇭' },
  { country: 'Qatar', code: 'QA', dial_code: '+974', flag: '🇶🇦' },
  { country: 'Russia', code: 'RU', dial_code: '+7', flag: '🇷🇺' },
  { country: 'Saudi Arabia', code: 'SA', dial_code: '+966', flag: '🇸🇦' },
  { country: 'Singapore', code: 'SG', dial_code: '+65', flag: '🇸🇬' },
  { country: 'South Africa', code: 'ZA', dial_code: '+27', flag: '🇿🇦' },
  { country: 'South Korea', code: 'KR', dial_code: '+82', flag: '🇰🇷' },
  { country: 'Spain', code: 'ES', dial_code: '+34', flag: '🇪🇸' },
  { country: 'Sri Lanka', code: 'LK', dial_code: '+94', flag: '🇱🇰' },
  { country: 'Sweden', code: 'SE', dial_code: '+46', flag: '🇸🇪' },
  { country: 'Switzerland', code: 'CH', dial_code: '+41', flag: '🇨🇭' },
  { country: 'Thailand', code: 'TH', dial_code: '+66', flag: '🇹🇭' },
  { country: 'Turkey', code: 'TR', dial_code: '+90', flag: '🇹🇷' },
  { country: 'United Arab Emirates', code: 'AE', dial_code: '+971', flag: '🇦🇪' },
  { country: 'United Kingdom', code: 'GB', dial_code: '+44', flag: '🇬🇧' },
  { country: 'United States', code: 'US', dial_code: '+1', flag: '🇺🇸' },
  { country: 'Vietnam', code: 'VN', dial_code: '+84', flag: '🇻🇳' }
];

export default Constcounty