import { StyleSheet, Platform } from "react-native";
import font from "../../../../theme/font";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 12,
    backgroundColor: "#fff",

  },

  topRow: {
    marginTop: 8,
    marginBottom: 4,
  },

  pill: {
    width: 180,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#FFD600",
    justifyContent: "center",
    overflow: "hidden",
  },
  pillHalf: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "50%",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  pillLeftText: {
    fontSize: 16,
    fontFamily: font.MonolithRegular,
  },
  pillRightText: {
    fontSize: 16,
    fontFamily: font.MonolithRegular,
  },
  knob: {
    position: "absolute",
    top: 4,
    bottom: 4,
    width: 80,
    borderRadius: 12,
    backgroundColor: "#fff",
  },
  onlineText: {
    marginTop: 8,
    fontSize: 12,
    fontFamily: font.MonolithRegular,
    textAlign: "center",
  },

  ordersHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 22,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    color: "black",
    fontFamily: font.MonolithRegular,
  },
  sectionTitle1: {
    fontSize: 15,
    color: "black",
    fontFamily: font.MonolithRegular,
  },

  tabs: {
    flexDirection: "row",
    backgroundColor: "#F5F5F5",
    padding: 6,
    borderRadius: 12,
    marginBottom: 12,
    height: 55,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
  },
  tabActive: {
    backgroundColor: "#FFCC00",
    height: 45,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  tabText: {
    fontSize: 14,
    color: "#1C1B1B",
    fontFamily: font.MonolithRegular,
  },
  tabTextActive: {
    color: "black",
    fontFamily: font.MonolithRegular,
    fontSize: 15,
  },
  container1: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  card1: {
    flex: 1,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#FFCC00",
    marginHorizontal: 6,
  },
  icon: {
    height: 28,
    width: 28,
    marginBottom: 11,
  },
  title: {
    color: "black",
    fontSize: 14,
    marginTop: 8,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,

    borderColor: "#E2E8F0",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.06,
        shadowRadius: 16,
      },

    }),
  },
  cardAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: "#FFCC00",
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    marginTop: 2,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    backgroundColor: "#FFF7CC",
    borderWidth: 1,
    borderColor: "#F4D45E",
  },
  cardHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  cardMetaLabel: {
    color: "#64748B",
    fontSize: 10,
    fontFamily: font.MonolithRegular,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  cardIdRow: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  cardId: {
    flexShrink: 1,
    fontSize: 16,
    color: "#0F172A",
  },
  bold: {
    fontFamily: font.MonolithRegular,
  },
  bulletSeparator: {
    marginHorizontal: 8,
    color: "#94A3B8",
    fontSize: 14,
    fontFamily: font.MonolithRegular,
  },
  cardDate: {
    flexShrink: 1,
    fontSize: 12,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
  },
  cardChevron: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#EEF2F7",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  timelineContainer: {
    width: 14,
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 3,
    height: 92,
    marginTop: 2,
  },
  timelineDotStart: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#FFCC00",
  },
  timelineLine: {
    flex: 1,
    width: 2,
    borderRadius: 1,
    backgroundColor: "#CBD5E1",
    marginVertical: 5,
  },
  timelineDotEnd: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#10B981",
  },
  routeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    paddingHorizontal: 14,
    paddingTop: 38,
    paddingBottom: 14,
    position: "relative",
    marginVertical: 4,
  },
  routeHeader: {
    position: "absolute",
    top: 11,
    left: 14,
    right: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  routeTitle: {
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    fontSize: 12,
  },
  routeBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EEF2F7",
  },
  routeContent: {
    flex: 1,
    marginLeft: 14,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 4,
  },
  dropLabelRow: {
    marginTop: 15,
  },
  label: {
    fontSize: 11,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  value: {
    fontSize: 14,
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    lineHeight: 19,
  },
  cardFooter: {
    alignSelf: "flex-end",
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFCC00",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 14,
    marginTop: 12,
  },
  footerText: {
    fontSize: 12,
    color: "#111827",
    fontFamily: font.MonolithRegular,
  },
  statusRow: {
    flexDirection: "row",
    marginTop: 10,
  },
  statusText: {
    fontSize: 12,
    color: "#555",
    marginRight: 6,
    fontFamily: font.MonolithRegular,
  },
  statusValue: {
    fontSize: 13,
    fontFamily: font.MonolithRegular,
  },
  emptyText: {
    textAlign: "center",
    marginTop: 40,
    color: "#9AA4AF",
    fontFamily: font.MonolithRegular,
  },
  emptyWrap: {
    paddingVertical: 60,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  illustrationWrap: {
    width: 160,
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    position: "relative",
  },
  illustrationBg: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "#FFCC00",
    opacity: 0.1,
  },
  emptyIcon: {
    height: 120,
    width: 120,
    resizeMode: "contain",
  },
  emptyTitle: {
    fontSize: 22,
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    marginBottom: 10,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 15,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    textAlign: "center",
    lineHeight: 22,
  },
});
