import { StyleSheet, Dimensions, Platform } from "react-native";
import font from "../../../../theme/font";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 15,
    backgroundColor: "#FFFFFF",
  },

  /* header */
  ordersHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 18,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    color: "#000",
    fontFamily: font.MonolithRegular,
  },

  /* summary cards */
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#000",
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 6,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  summaryTitle: {
    color: "#EDEDED",
    fontSize: 14,
    marginTop: 8,
    fontFamily: font.MonolithRegular,
  },
  summaryValue: {
    marginTop: 5,
    color: "#FFF",
    fontSize: 18,
    fontFamily: font.MonolithRegular,
  },

  /* tabs */
  tabs: {
    flexDirection: "row",
    backgroundColor: "#F5F5F5",
    padding: 10,
    borderRadius: 20,
    marginBottom: 12,
    alignItems: "center",
    marginTop: 12,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: {
    backgroundColor: "#FFCC00",
    height: 40,
  },
  tabText: {
    fontSize: 13,
    color: "#1C1B1B",
    fontFamily: font.MonolithRegular,
  },
  tabTextActive: {
    color: "#FFF",
    fontSize: 15,
    fontFamily: font.MonolithRegular,
  },

  /* cards */
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.06,
        shadowRadius: 16,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  cardAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: "#FFCC00",
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
    marginTop: 2,
  },
  headerLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  avatarWrap: {
    width: 46,
    height: 46,

  },
  avatar: {
    height: 34,
    width: 34,
    borderRadius: 17,
    backgroundColor: "#F1F5F9",
  },
  userInfo: {
    flex: 1,
    paddingRight: 10,
    minWidth: 0,
  },
  userMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 3,
  },
  userLabel: {
    fontSize: 10,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    textTransform: "uppercase",
  },
  orderCode: {
    flex: 1,
    fontSize: 10,
    color: "#94A3B8",
    fontFamily: font.MonolithRegular,
  },
  name: {
    fontSize: 16,
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
  },
  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
    gap: 4,
  },
  phone: {
    flex: 1,
    fontSize: 12,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
  },
  statusPill: {
    paddingHorizontal: 10,
    height: 24,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  statusPillText: {
    fontSize: 11,
    fontFamily: font.MonolithRegular,
  },
  code: {
    marginLeft: 52, // align under name (40 avatar + 12 gap)
    fontSize: 12,
    color: "#9AA4AF",
    fontFamily: font.MonolithRegular,
  },
  trackingText: {
    marginLeft: 52,
    fontSize: 12,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
  },
  statusChip: {
    maxWidth: 116,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 99,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    fontFamily: font.MonolithRegular,
    fontSize: 11,
    letterSpacing: 0,
  },
  splitter: {
    display: "none",
  },
  stopsRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    paddingHorizontal: 14,
    paddingTop: 38,
    paddingBottom: 14,
    position: "relative",
    marginVertical: 4,
  },
  routeHeader: {
    position: "absolute",
    top: 11,
    left: 14,
    right: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  routeTitle: {
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    fontSize: 12,
  },
  routeBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#EEF2F7",
  },
  timelineContainer: {
    width: 14,
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 3,
    height: 92,
    marginTop: 2,
  },
  timelineDotStart: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#FFCC00",
  },
  timelineLine: {
    flex: 1,
    width: 2,
    borderRadius: 1,
    backgroundColor: "#CBD5E1",
    marginVertical: 5,
  },
  timelineDotEnd: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#10B981",
  },
  stopsContent: {
    flex: 1,
    marginLeft: 14,
  },
  stopLabel: {
    fontSize: 11,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  stopLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 4,
  },
  dropLabelRow: {
    marginTop: 15,
  },
  stopValue: {
    fontSize: 14,
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    lineHeight: 19,
  },
  offerBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 13,
    borderRadius: 14,
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FDE68A",
    position: "relative",
    marginTop: 4,
    marginBottom: 15,
    overflow: "hidden",
  },
  offerAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: "#F59E0B",
  },
  offerInfo: {
    flex: 1,
    paddingLeft: 5,
  },
  offerHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  offerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFCC00",
    alignItems: "center",
    justifyContent: "center",
  },
  offerIconText: {
    fontSize: 17,
    color: "#111827",
    fontFamily: font.MonolithRegular,
  },
  offerHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  offerEyebrow: {
    fontSize: 10,
    color: "#92400E",
    fontFamily: font.MonolithRegular,
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  offerBadge: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "#F59E0B",
  },
  offerBadgeText: {
    fontSize: 9,
    color: "#FFF",
    fontFamily: font.MonolithRegular,
  },
  offerTitle: {
    fontSize: 13,
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    marginTop: 3,
  },
  offerAmountPill: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#111827",
  },
  offerAmount: {
    fontSize: 15,
    color: "#FFFFFF",
    fontFamily: font.MonolithRegular,
  },
  offerHint: {
    fontSize: 12,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    lineHeight: 16,
    flexShrink: 1,
  },
  offerActionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 13,
  },
  acceptOfferBtn: {
    flex: 1.15,
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: "#FFCC00",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  cancelOfferBtn: {
    flex: 1,
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: "#FFF1F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  replyOfferBtn: {
    flex: 1,
    minHeight: 38,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  acceptOfferBtnDisabled: {
    opacity: 0.65,
  },
  acceptOfferText: {
    fontSize: 13,
    color: "#111827",
    fontFamily: font.MonolithRegular,
  },
  cancelOfferText: {
    fontSize: 13,
    color: "#DC2626",
    fontFamily: font.MonolithRegular,
  },
  replyOfferText: {
    fontSize: 13,
    color: "#334155",
    fontFamily: font.MonolithRegular,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 14,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  footerStatusRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  footerStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  footerStatusText: {
    flex: 1,
    minWidth: 0,
  },
  footerLabel: {
    fontSize: 10,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    marginBottom: 2,
  },
  footerValue: {
    flex: 1,
    fontSize: 12,
    fontFamily: font.MonolithRegular,
  },
  viewDetailsButton: {
    backgroundColor: "#FFCC00",
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 14,
    marginLeft: 10,
  },
  viewDetailsText: {
    fontSize: 12,
    color: "#111827",
    fontFamily: font.MonolithRegular,
  },

  emptyWrap: {
    paddingVertical: 60,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  illustrationWrap: {
    width: 160,
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    position: "relative",
  },
  illustrationBg: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "#FFCC00",
    opacity: 0.1,
  },
  emptyIcon: {
    height: 120,
    width: 120,
    resizeMode: "contain",
  },
  emptyTitle: {
    fontSize: 22,
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    marginBottom: 10,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 15,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    textAlign: "center",
    lineHeight: 22,
  },
});
