import { Platform, StyleSheet } from "react-native";
import font from "../../../theme/font";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 120,
  },
  heroCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111827",
    borderRadius: 24,
    padding: 18,
    overflow: "hidden",
  },
  heroIconWrap: {
    width: 74,
    height: 74,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,

  },
  heroIcon: {
    width: 52,
    height: 52,
  },
  heroTextWrap: {
    flex: 1,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontFamily: font.MonolithRegular,
  },
  heroSubtitle: {
    color: "#D1D5DB",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 7,
    fontFamily: font.MonolithRegular,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    marginVertical: 22,
    width: "70%",
  },
  progressStep: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    justifyContent: "center",
    alignItems: "center",
  },
  progressDone: {
    backgroundColor: "#22C55E",
    borderColor: "#22C55E",
  },
  progressActive: {
    backgroundColor: "#FFCC00",
    borderColor: "#FFCC00",
  },
  progressStepText: {
    color: "#111827",
    fontSize: 13,
    fontFamily: font.MonolithRegular,
  },
  progressStepMuted: {
    color: "#9CA3AF",
    fontSize: 13,
    fontFamily: font.MonolithRegular,
  },
  progressLine: {
    flex: 1,
    height: 2,
    backgroundColor: "#E5E7EB",
  },
  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#EEF0F3",
    padding: 18,
    ...Platform.select({
      ios: {
        shadowColor: "#111827",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.08,
        shadowRadius: 20,
      },

    }),
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 18,
    fontFamily: font.MonolithRegular,
    marginBottom: 18,
  },
  fieldLabel: {
    color: "#4B5563",
    fontSize: 13,
    fontFamily: font.MonolithRegular,
    marginBottom: 9,
    marginTop: 2,
  },
  dropdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",

    borderRadius: 16,
    paddingHorizontal: 14,
    height: 62,
    marginBottom: 17,
    backgroundColor: "#F9FAFB",
  },
  dropdownLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 12,
  },
  fieldIconBox: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 11,
    borderWidth: 1,
    borderColor: "#EEF0F3",
  },
  fieldIconBoxActive: {
    backgroundColor: "#FFF7CC",
    borderColor: "#FFE680",
  },
  dropdownText: {
    color: "#111827",
    fontSize: 15,
    fontFamily: font.MonolithRegular,
    flex: 1,
  },
  placeholderText: {
    color: "#9CA3AF",
  },
  arrowIcon: {
    height: 18,
    width: 18,
    tintColor: "#6B7280",
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",

    borderRadius: 16,
    paddingHorizontal: 14,
    height: 62,
    marginBottom: 18,
    backgroundColor: "#F9FAFB",
  },
  inputActive: {
    borderColor: "#FFCC00",
    backgroundColor: "#FFFFFF",
  },
  input: {
    flex: 1,
    paddingVertical: 0,
    fontSize: 15,
    color: "#111827",
    fontFamily: font.MonolithRegular,
    letterSpacing: 0,
  },
  uploadBox: {
    minHeight: 178,
    borderColor: "#CBD5E1",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderStyle: "solid",
    backgroundColor: "#F9FAFB",

  },
  uploadBoxFilled: {
    height: 214,
    borderStyle: "solid",
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    padding: 6,
  },
  uploadEmpty: {
    alignItems: "center",
    paddingHorizontal: 20,
  },
  uploadIconCircle: {

    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    padding: 15,


  },
  uploadIcon: {
    width: 26,
    height: 26,
    tintColor: "#FFCC00",
  },
  uploadText: {
    color: "#111827",
    fontSize: 15,
    fontFamily: font.MonolithRegular,
    textAlign: "center",
  },
  uploadHint: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    fontFamily: font.MonolithRegular,
    textAlign: "center",
  },
  buttonContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: Platform.OS === "ios" ? 10 : 16,
    backgroundColor: "rgba(255,255,255,0.96)",

  },
  button: {
    backgroundColor: "#FFCC00",
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  buttonText: {
    color: "#000",
    fontSize: 16,
    fontFamily: font.MonolithRegular,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.42)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  dropdownContainer: {
    backgroundColor: "#fff",
    borderRadius: 22,
    width: "100%",
    paddingVertical: 8,
    overflow: "hidden",
  },
  dropdownHeader: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  dropdownTitle: {
    fontSize: 16,
    color: "#111827",
    fontFamily: font.MonolithRegular,
  },
  dropdownItem: {
    minHeight: 64,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownItemSelected: {
    backgroundColor: "#FFFCF0",
  },
  dropdownItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  vehicleIconBox: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  vehicleIconBoxActive: {
    backgroundColor: "#FFE680",
  },
  dropdownItemText: {
    fontSize: 15,
    color: "#374151",
    fontFamily: font.MonolithRegular,
  },
  dropdownItemTextSelected: {
    color: "#111827",
  },
  dropdownSeparator: {
    height: 1,
    backgroundColor: "#F3F4F6",
    marginLeft: 68,
  },
  previewImage: {
    width: "100%",
    height: "100%",
    borderRadius: 14,
    resizeMode: "cover",
  },
  previewContainer: {
    width: "100%",
    height: "100%",
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: "#F3F4F6",
  },
  pdfPreview: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFCF0",
    borderRadius: 14,
  },
  icon: {
    height: 40,
    width: 40,
    tintColor: "#FFB800",
  },
  previewOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 54,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(17,24,39,0.78)",
  },
  previewInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 10,
  },
  previewName: {
    color: "#FFFFFF",
    fontSize: 13,
    marginLeft: 8,
    flex: 1,
    fontFamily: font.MonolithRegular,
  },
  changePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFCC00",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 14,
  },
  changeText: {
    color: "#111827",
    fontSize: 11,
    marginLeft: 4,
    fontFamily: font.MonolithRegular,
  },
  modal: {
    justifyContent: "flex-end",
    margin: 0,
  },
  modalContent: {
    backgroundColor: "#fff",
    paddingBottom: Platform.OS === "ios" ? 42 : 30,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingHorizontal: 20,
  },
  modalHandle: {
    width: 42,
    height: 5,
    borderRadius: 5,
    backgroundColor: "#E5E7EB",
    alignSelf: "center",
    marginTop: 12,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: font.MonolithRegular,
    color: "#333",
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBody: {
    marginTop: 10,
  },
  optionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
  },
  optionIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  optionText: {
    fontSize: 16,
    fontFamily: font.MonolithRegular,
    color: "#444",
  },
  optionSubText: {
    color: "#8F8F8F",
    fontSize: 12,
    marginTop: 3,
    fontFamily: font.MonolithRegular,
  },
});
