import { StyleSheet } from "react-native";
import font from "../../../../theme/font";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F6F9",
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,

  },
  cardTitle: {
    fontSize: 17,
    color: "#1E293B",
    fontFamily: font.MonolithRegular,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    marginTop: 20,
    marginBottom: 10,
    color: "black",
    fontFamily: font.MonolithRegular
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 8,
    fontFamily: font.MonolithRegular,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 16,
    minHeight: 56,
    backgroundColor: "#F8FAFC",
    flexDirection: "row",
    alignItems: "center",
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: "#F8FAFC",
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    fontSize: 15,
  },
  textArea: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    minHeight: 100,
    backgroundColor: "#F8FAFC",
    color: "#0F172A",
    fontFamily: font.MonolithRegular,
    fontSize: 15,
    textAlignVertical: "top",
  },
  placeholderText: {
    color: "#94A3B8",
    fontSize: 15,
    fontFamily: font.MonolithRegular,
    flex: 1,

  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  halfInput: {
    width: "48%",
  },
  packageRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  packageBox: {
    width: "31%",
    paddingVertical: 16,
    borderWidth: 1.5,
    borderRadius: 12,
    borderColor: "#F1F5F9",
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
  },
  packageText: {
    fontSize: 13,
    color: "#64748B",
    fontFamily: font.MonolithRegular,
    textAlign: "center",
    marginTop: 8,
  },
  selectedBox: {
    borderColor: "#FFCC00",
    backgroundColor: "#FFFBE6",
  },
  selectedText: {
    color: "#B28E00",
    fontFamily: font.MonolithRegular,
  },
  submitBtnContainer: {
    marginBottom: 50,
    marginTop: 11,
  },
  submitBtn: {
    marginTop: 30,
    backgroundColor: "#FFCC00",
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: "center",
  },
  submitText: {
    fontSize: 16,
    fontFamily: font.MonolithRegular,
    color: "#000",
  },
  inputError: {
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 4,
    fontFamily: font.MonolithRegular,
  },
  imageUploadButton: {
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderStyle: "dashed",
    backgroundColor: "#F8FAFC",
    paddingVertical: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    marginTop: 5,
    marginBottom: 11,
  },
  imageUploadPlaceholderText: {
    fontSize: 15,
    fontFamily: font.MonolithRegular,
    color: "#475569",
    marginTop: 10,
  },
  imageUploadSubText: {
    fontSize: 12,
    fontFamily: font.MonolithRegular,
    color: "#94A3B8",
    marginTop: 4,
  },
  imagePreviewContainer: {
    position: "relative",
    width: "100%",
    height: 160,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    marginTop: 5,
    marginBottom: 11,
  },
  parcelImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  imageEditBadge: {
    position: "absolute",
    bottom: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  imageEditBadgeText: {
    fontSize: 12,
    fontFamily: font.MonolithRegular,
    color: "#0F172A",

  },
  iconLocation: {
    height: 26,
    width: 26,
  },
  phoneInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: "#F8FAFC",
  },
  countryPicker: { marginRight: 5, alignItems: "center", flexDirection: "row" },
  callingCode: { fontSize: 15, color: "black", fontFamily: font.MonolithRegular },
  separator: { borderWidth: 0.5, height: 22, borderColor: "#E2E8F0", marginLeft: 5 },
  phoneInput: { fontFamily: font.MonolithRegular, flex: 1, height: 56, fontSize: 15, color: "#0F172A", marginLeft: 5 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", alignItems: "center" },
  modalContent: {
    backgroundColor: "#fff",
    width: "88%",
    borderRadius: 18,
    maxHeight: "52%",
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 15 },
  modalTitle: { fontFamily: font.MonolithRegular, fontSize: 18, color: "#000" },
  modalCancel: { fontFamily: font.MonolithRegular, fontSize: 15, color: "#FFCC00" },
  searchInput: { fontFamily: font.MonolithRegular, borderWidth: 1, borderColor: "#ccc", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, color: "#000" },
  modalItem: { paddingVertical: 12, borderBottomWidth: 0.5, borderBottomColor: "#ddd" },
  countryText: { fontSize: 16, color: "#000", fontFamily: font.MonolithRegular },
});
