import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    ChangeLanguage: "Change Language",
    Logout: "Log Out",
    LogoutConfirmMessage: "Are you sure you want to log out of your account?",
    PhysicalData: "Physical Data",
    UsefulTips: "Useful Tips",
    PaymentHistory: "Payment History",
    Camera: "Camera",
    ViewAll: "View All",
    Gallery: "Gallery",
    Account: "Account Settings",
    Support: "Support & Legal"
    ,
    Locationu: "Location unavailable",
    Help: "Help",
    ContactInfo: "Contact Info",
    PushNotifications: "Push Notifications",
    UpdateProfile: "Update Profile",
    Version: "Version",
    Profile: "Profile",
    Add: "Add",
    Rating: "Thanks for your rating!",
    RatingLabel: "Rating",
    ReviewsLabel: "Reviews",
    TypeAMessagePlaceholder: "Type a message...",
    // Onboarding
    ShipYourParcel: "Ship Your Parcel",
    ShipAnywhere: "Ship Anywhere",
    TrackYourParcel: "Track Your Parcel",
    OnboardingDesc1: "Experience smooth and completely stress-free shipping of your parcel.",
    OnboardingDesc2: "Send your parcel across borders with our reliable and secure shipping service.",
    OnboardingDesc3: "Stay updated and know the real-time location of your shipment anytime.",
    Skip: "Skip",
    Continue: "Continue",
    // Choose Role
    ChooseRole: "Choose your user Role",
    User: "User",
    Delivery: "Delivery",
    PleaseSelectRole: "Please select your role before proceeding.",
    // Profile
    EditProfile: "Edit Profile",
    MyOrders: "My Orders",
    PrivacyPolicy: "Privacy Policy",
    TermsConditions: "Terms and Conditions",
    // Login
    PhoneQuestion: "What's your phone number?",
    PhoneSubtitle: "We'll send you a code to verify it",
    PhoneNumber: "Phone Number",
    SelectCountry: "Select Country",
    SearchCountry: "Search country",
    Cancel: "Cancel",
    PleaseEnterPhone: "Please enter your phone number.",
    PleaseEnterValidPhone: "Please enter a valid phone number (6-15 digits).",
    ContinueWithNumber: "Continue with Number",
    ContinueWithGoogle: "Continue with Google",
    FullName: "Full Name",
    Email: "Email",
    Address: "Address",
    Update: "Update",
    // Status Labels
    StatusPending: "Pending",
    StatusAssigned: "Assigned",
    StatusGoingToPickup: "Going to Pickup",
    StatusPickedUp: "Picked Up",
    StatusOnTheWay: "On the Way",
    StatusArriving: "Arriving",
    StatusDelivered: "Delivered",
    StatusCompleted: "Completed",
    StatusCancelled: "Cancelled",
    // Orders Screen
    Orders: "Orders",
    Pending: "Pending",
    Complete: "Complete",
    Canceled: "Canceled",
    NoOrdersFound: "No orders found",
    NoOrdersHereYet: "No orders here yet.",
    NoOrder: "No Active Orders",
    NoOrdersFound1: "Your shipping history is empty. Start by creating your first parcel request.",
    TrackingID: "Tracking ID",
    StepXofY: "Step {0} of {1} complete",
    ViewDetails: "View Details",
    WriteAReview: "Write a Review",
    // General
    Search: "Search",
    Notifications: "Notifications",
    Home: "Home",
    Messages: "Messages",
    Tracking: "Tracking",
    From: "From",
    To: "To",
    DeliveryStatus: "Delivery Status",
    CreateParcel: "Create Parcel",
    ShippingHistory: "Shipping History",
    SelectDeliveryAddress: "Select your delivery address",
    OfferAccepted: "Offer Accepted",
    DriverAcceptedOffer: "Driver has accepted your counter offer.",
    Order: "Order",
    Carrier: "Carrier",
    OfferPrice: "Offer Price",
    MessageLabel: "Message",
    PhoneLabel: "Phone",
    Accept: "Accept",
    CounterOfferLabel: "COUNTER OFFER",
    Chat: "CHAT",
    Back: "Back",
    OffersForYourAd: "OFFERS FOR YOUR AD",
    OfferInformation: "Offer Information",
    ProposedAmount: "Proposed Amount",
    NoOffersAvailable: "No offers available for your ad yet.",
    FindingDriver: "Finding Driver",
    DriversLabel: "DRIVERS",
    RadiusLabel: "RADIUS",
    ScanningArea: "SCANNING AREA",
    CancelSearch: "CANCEL SEARCH",
    RetryLabel: "RETRY",
    SearchingDrivers: "Searching for available drivers...",
    ConnectingNetwork: "Connecting to delivery network",
    DriverConfirmed: "Driver confirmed • Preparing pickup",
    DriverEnRoute: "Driver en route • ETA calculating",
    ParcelCollected: "Parcel collected • In transit",
    ParcelDelivered: "Parcel delivered successfully",
    SearchInboxPlaceholder: "Search by name",
    NoChatsYet: "No chats yet",
    NoConversationsSubtitle: "Your conversations will appear here",
    ActiveDeliveryConversations: "{0} active delivery conversations",
    NoActiveDeliveryChats: "No active delivery chats",
    SessionExpired: "Session expired. Please log in again.",
    FailedLoadChats: "Failed to load chats. Pull down to retry.",
    NoMessagesYet: "No messages yet",
    Unknown: "Unknown",
    Today: "Today",
    Yesterday: "Yesterday",
    DeliveryAgent: "Delivery Agent",
    TypeAMessage: "Type a message…",
    LoadingMessages: "Loading messages…",
    NoMessagesYetSayHi: "No messages yet. Say hi!",
    OrderOpen: "Order Open",
    ErrorLabel: "Error",
    PhoneNotAvailable: "Phone number not available",
    PhoneCallNotSupported: "Phone call not supported",
    SomethingWentWrong: "Something went wrong",
    FailedAcceptOffer: "Failed to accept offer",
    Done: "Done",
    SelectLanguage: "Select Language",
    FailedSendCounterOffer: "Failed to send counter offer",
    CounterOfferSent: "Counter offer sent successfully!",
    OfferAcceptedSuccess: "Offer accepted successfully!",
    InvalidOfferId: "Invalid offer ID",
    NewTipsAvailable: "New Tips Available",
    EnterVerificationCode: "Enter the verification code",
    SentCodeTo: "We sent you a 4-digit code to {0}",
    DidntReceiveOTP: "Didn’t receive the OTP?",
    ResendIn: "Resend in",
    ResendOTPButton: "RESEND OTP",
    NoContentAvailable: "No content available",
    LoginSuccess: "OTP sent successfully!",
    LoginFailed: "Login failed. Please try again.",
    VerificationSuccess: "Login successful!",
    InvalidOTP: "Invalid OTP. Please try again.",
    ResendSuccess: "OTP resent successfully!",
    ResendFailed: "Failed to resend OTP. Please try again.",
    // Document Show
    MyDocuments: "My Documents",
    DocumentShowSubtitle: "Review your identity, vehicle, and payout details in one place.",
    DocumentUploaded: "Document uploaded",
    UploadIdentityDocuments: "Upload Identity Documents",
    SetUpVehicleDetails: "Set Up Vehicle Details",
    SetUpBankDetails: "Set Up Bank Details",
    Identity: "Identity",
    Vehicle: "Vehicle",
    Banking: "Banking",
    Identification: "Identification",
    DrivingLicense: "Driving License",
    IDDocument: "ID Document",
    VehiclePapers: "Vehicle Papers",
    TapToEnlarge: "Tap to enlarge",
    VehicleInformation: "Vehicle Information",
    VehicleType: "Vehicle Type",
    VehicleNumber: "Vehicle Number",
    Model: "Model",
    Color: "Color",
    RegistrationPaper: "Registration Paper",
    YourBank: "Your Bank",
    AccountNumber: "Account Number",
    AccountHolder: "Account Holder",
    IFSCCode: "IFSC Code",
    Verified: "Verified",
    InReview: "In Review",
    Pending: "Pending",
    FetchingDetails: "Fetching details...",
    NoDataFound: "No Data Found",
    InfoWillAppearHere: "Information will appear here once it has been processed.",
    // Delivery Side
    EarningsReports: "Earnings & Reports",
    DocumentShow: "Document Show",
    Wallet: "Wallet",
    Support: "Support",
    ShareApp: "Suggest to others",
    TodaysEarnings: "Today's Earnings",
    PendingRides: "Pending Rides",
    TodaysRides: "Today's Rides",
    WeeklyEarnings: "Weekly's Earnings",
    WeeklyRides: "Weekly's Rides",
    PickupFrom: "PICKUP FROM",
    DeliverTo: "DELIVER TO",
    RouteMap: "Route Map",
    DeliverySchedule: "Delivery Schedule",
    PickupDate: "Pickup Date",
    PickupTime: "Pickup Time",
    OfferStatus: "Offer Status",
    Reject: "Reject",
    AcceptDelivery: "Accept Delivery",
    RejectDelivery: "Reject Delivery",
    RejectDeliveryConfirm: "Are you sure you want to reject this delivery?",
    TotalEarnings: "Total Earnings",
    Activity: "Activity",
    OnlineHrs: "Online Hrs",
    Trips: "Trips",
    CashTrip: "Cash Trip",
    HowCanWeHelp: "How can we help?",
    TypeHere: "Type Here...",
    Submit: "Submit",
    AvailableBalance: "Your Available Balance",
    Withdraw: "Withdraw",
    AddAmount: "Add Amount",
    AddMoney: "Add Money",
    WithdrawMoney: "Withdraw Money",
    EnterAmount: "Enter Amount",
    Confirm: "Confirm",
    Sun: "SUN",
    Mon: "MON",
    Tue: "TUE",
    Wed: "WED",
    Thu: "THU",
    Fri: "FRI",
    Sat: "SAT",
    SuccessLabel: "Success",
    DeliveryAcceptedSuccess: "Delivery accepted successfully!",
    FailedLoadOrders: "Failed to fetch order details",
    SendOffer: "Send Offer",
    StartPickup: "Start Pickup",
    MarkAsPickedUp: "Mark as Picked Up",
    StartDelivery: "Start Delivery",
    MarkAsDelivered: "Mark as Delivered",
    OrderCompleted: "Order Completed",
    OrderCancelled: "Order Cancelled",
    Processing: "Processing...",
    PickupOtpError: "Please enter pickup OTP shared by customer",
    DeliveryOtpError: "Please enter delivery OTP shared by customer",
    ParcelDetails: "Parcel Details",
    PickupLocation: "Pickup Location",
    DropLocation: "Drop Location",
    ParcelInformation: "Parcel Information",
    Price: "Price",
    SenderName: "Sender Name",
    ReceiverName: "Receiver Name",
    ReceiverPhone: "Receiver Phone",
    PackageSize: "Package Size",
    ConsignmentType: "Consignment Type",
    ShipmentType: "Shipment Type",
    MakeOffer: "Make Offer",
    AmountWithCurrency: "Amount ₮",
    EnterValidAmount: "Please enter a valid amount",
    MinimumIs: "Minimum is",
    MaximumIs: "Maximum is",
    TypeMessageHere: "Type your message here...",
    CancelOrderConfirm: "Are you sure you want to cancel this order?",
    CreateAccount: "Create an account",
    AlreadyHaveAccount: "Already have an account",
    EnterFullNameError: "Please enter your full name.",
    EnterEmailError: "Please enter your email address.",
    ValidEmailError: "Please enter a valid email address.",
    EnterAddressError: "Please enter your address.",
    UploadProfileImageError: "Please upload your profile image.",
    UploadDocuments: "Upload Documents",
    UploadIdDocument: "Upload ID Document",
    UploadDrivingLicense: "Upload Driving License",
    UploadVehiclePapers: "Upload Vehicle Papers",
    UploadDocumentsError: "Please upload all required documents.",
    DrivingLicenseNumber: "Driving License Number",
    BankName: "Bank Name",
    AccountNumber: "Account Number",
    IFSCCode: "IFSC Code",
    EnterLicenseNumberError: "Please enter your driving license number.",
    EnterPhoneNumberError: "Please enter your phone number.",
    EnterBankNameError: "Please enter your bank name.",
    EnterAccountNumberError: "Please enter your bank account number.",
    EnterIFSCCodeError: "Please enter your bank's IFSC code.",
    VehicleSetup: "Vehicle Setup",
    VehicleSetupSubtitle: "Add your vehicle details and registration to continue verification.",
    SelectVehicleType: "Select vehicle type",
    EnterVehicleNumber: "Enter vehicle number",
    UploadVehicleRegistration: "Upload vehicle registration",
    VehicleUploadHint: "Camera or gallery image accepted",
    Change: "Change",
    TakeClearPhoto: "Take a clear photo",
    ChooseFromPhone: "Choose from your phone",
    RemoveSelectedDocument: "Remove selected document",
    SelectVehicleTypeError: "Please select a vehicle type.",
    EnterVehicleNumberError: "Please enter the vehicle number.",
    UploadVehicleRegistrationError: "Please upload vehicle registration.",
    SaveAndContinue: "Save & Continue",
    Car: "Car",
    Bike: "Bike",
    Van: "Van",
    Truck: "Truck",
    Confirmation: "Confirmation",
    Yes: "Yes",
    No: "No",
    BankSetup: "Bank Setup",
    BankSetupSubtitle: "Add the bank account where your delivery payouts should be sent.",
    BankSecureNote: "Secure details",
    PayoutReady: "Payout account information",
    EnterBankName: "Enter bank name",
    EnterAccountNumber: "Enter account number",
    EnterIFSCCode: "Enter IFSC code",
    SaveAndFinish: "Save & Finish",
    Message: "Message",
    RateYourDelivery: "Rate your delivery",
    ViewOffer: "View Offer",
    TrackDetail: "Track Detail",
    TrackingPackage: "Tracking Package",
    RatingSuccess: "Thanks for your rating!",
    RatingPoor: "Poor",
    RatingFair: "Fair",
    RatingGood: "Good",
    RatingGreat: "Great",
    RatingExcellent: "Excellent",
    HowWasExperience: "How was your experience?",
    ShareExperiencePlaceholder: "Share your experience (optional)",
    ParcelUpdated: "Parcel updated",
    OrderNumber: "Order Number: ",
    OK: "OK",
    PickupAndDrop: "Pickup & Drop",
    AddPickupLocation: "Add Pickup Location",
    AddDropLocation: "Add Drop Location",
    ShipmentSenderDetails: "Shipment & Sender Details",
    SenderMobileNumber: "Sender Mobile Number",
    ReceiverDetails: "Receiver Details",
    ReceiverMobileNumber: "Receiver Mobile Number",
    ExtraMessage: "Extra Message",
    AddParcelImage: "Add Parcel Image",
    SendRequest: "Send Request",
    Standard: "Standard",
    Express: "Express",
    Normal: "Normal",
    Fast: "Fast",
    OrderCancelled: "Order cancelled successfully",

    PickupLocationRequired: "Pickup location is required",
    DropLocationRequired: "Drop location is required",
    PickupRequestSuccess: "Pickup request submitted successfully!",
    FillRequiredFieldsError: "Please fill all required fields correctly",
    AssigningDriver: "Assigning driver...",
    OTP: "OTP",
    Size: "Size",
    Type: "Type",
    Service: "Service",
    Pickup: "Pickup",
    Drop: "Drop",
    Calculating: "Calculating...",
    DeliveryType: "Delivery Type",
    Slide: "Slide",
    AddAddress: "Add Address",
    HomeType: "Home",
    OfficeType: "Office",
    OfferAcceptedFailed: "Failed to accept offer",
    CounterOfferFailed: "Failed to send counter offer",
    InvalidOfferID: "Invalid offer ID",
    Error: "Error",
    PhoneNotAvailable: "Phone number not available",
    PhoneCallNotSupported: "Phone call not supported",
    ThisWeek: "This Week",
    GeneralNotification: "General Notification",
    Sound: "Sound",
    Sound: "Sound",
    Vibrate: "Vibrate",
    // Location & Search
    Locating: "Locating...",
    UnknownLocation: "Unknown Location",
    PermissionDenied: "Location permission denied",
    UnableGetLocation: "Unable to get location",
    SearchPickupArea: "Search Pickup Area",
    SetPickup: "Set Pickup",
    ConfirmLocation: "Confirm Location",
    SearchAddress: "Search Address",
    EnterAddressPlaceholder: "Enter your address...",
    SearchingNearby: "Searching nearby...",
    NoResultsRegion: "No results in this region",
    // Image Picker
    ChooseOption: "Choose an Option",
    SelectGallery: "Select from Gallery",
    TakePhoto: "Take a Photo",
    Remove: "Remove",
    DocumentLabel: "Document",
    ParcelLabel: "Parcel",
    SmallSize: "1 KG",
    MediumSize: "3KG - 10KG",
    LargeSize: "10KG+",
    NoInternetConnection: "No Internet! Please check your connection.",
    BackOnline: "Back Online",
    CheckWifiData: "Please check your Wi-Fi or mobile data",
    Enter4DigitOTP: "Please enter 4 digit OTP",
    InvalidServerResponse: "Invalid server response",
    NetworkErrorTryAgain: "Network error. Please try again.",
    SomethingWentWrong: "Something went wrong. Please try again.",
    ValueNotFound: "Value not found",
    TokenNotFound: "Token not found",
    EnterPickupOTP: "Please enter pickup OTP shared by customer",
    EnterAmount: "Please enter amount",
    EnterMessage: "Please enter message",
    ErrorPickingImage: "Error picking image",
    ErrorPickingDocument: "Error picking document",
    SelectDocument: "Select Document",
    Confirmation: "Confirmation",
    AreYouSureCancel: "Are you sure you want to cancel?",
    OrderCompleted: "Order Completed",
    OrderCancelled: "Order Cancelled",
    Processing: "Processing...",
    Reply: "Reply",
    EnterPickupOTPShared: "Enter Pickup OTP shared by customer",
    EnterDeliveryOTPShared: "Enter delivery OTP shared by customer",
    CancelOrder: "Cancel Order",
    RateDelivery: "Rate delivery",
    NextStep: "Next Step: {0}",
    FailedUpdateStatus: "Failed to update status",
    EnterOTP: "Enter OTP",
    ConnectionErrorRetrying: "Connection error. Retrying...",
    ConnectionFailedTryAgain: "Connection failed. Please try again.",
    FailedConnectCheckInternet: "Failed to connect. Please check your internet.",
    AuthTokenNotFound: "Authentication token not found",
    ParcelIDNotFound: "Parcel ID not found",
    NoPartnerAccepted: "No partner accepted",
    NoPartnerAcceptedDesc: "No delivery partner accepted in 30 seconds. Tap Try again to search again or go back.",
    PleaseWaitFindingPartner: "Please wait while we find the nearest partner",
    CurrentLocation: "Current location",
    XSecLeft: "{0} sec left",
    LanguageSelectionTitle: "Choose your language to start your journey with us.",
    LanguageSelectionUpdate: "Update your language preference for the app display.",
    StartPickup: "Start Pickup",
    MarkPickedUp: "Mark as Picked Up",
    StartDelivery: "Start Delivery",
    MarkDelivered: "Mark as Delivered",
    StatusUpdatedTo: "Success, Status updated to {0}",
    NewDeliveryRequest: "New parcel request",

    CounterOfferReceived: "Counter Offer Received",
    CounterOfferMessage: "User sent a counter offer. Tap to view and respond.",
    UserOfferedNewPrice: "User has offered a new price",
    ReviewAcceptDeliveryOffer: "Review and accept to confirm this delivery offer.",
    NewDeliveryRequestMessage: "A parcel pickup is nearby. Tap below to see details and send your offer.",
    Later: "Later",
    UpdateAvailableTitle: "Update Available",
    UpdateAvailableMessage: "A new version of Daina is available. Please update the app for the latest features and bug fixes.",
    UpdateNow: "Update Now",
    VersionUpdateText: "Current {0} - Latest {1}",
    ViewOrder: "View order",
    NoNotifications: "No notifications found",
    FileTooLarge: "File size is too large for upload. Please select a smaller file.",
    SlideToGoOnline: "Slide to go online",
    SlideToGoOffline: "Slide to go offline",
    VerificationTitle: "Account Verification",
    VerificationSubtitle: "Your documents are currently under review by our admin team.",
    VerificationDescription: "This process usually takes 24-48 hours. We'll notify you as soon as your account is activated. Thank you for your patience!",
    VerificationPending: "Verification Pending",
    InProgress: "In Progress",
    PendingApproval: "PENDING APPROVAL",
    VerificationPendingDesc: "Your application is in the final stages of review. We will notify you once you're ready to start.",
    ReviewProgress: "Review Progress",
    DocumentsUploaded: "Documents Uploaded",
    DocumentsUploadedDesc: "ID, Driving License & Vehicle papers",
    AdminVerification: "Admin Verification",
    AdminVerificationDesc: "Manual check of submitted documents",
    BackgroundCheck: "Background Check",
    BackgroundCheckDesc: "Safety and compliance verification",
    ReadyForOrders: "Ready for Orders",
    ReadyForOrdersDesc: "Access to parcel delivery requests",
    DidYouKnow: "Did you know?",
    VerificationTip: "Complete profiles are 3x faster to verify. Make sure your photos are clear and readable.",
    RefreshStatus: "Refresh Status",
    DeleteAccount: "Delete Account",
    DeleteAccountConfirmTitle: "Delete Account",
    DeleteAccountConfirmMessage: "Are you sure you want to delete your account? This action cannot be undone and all your data will be permanently removed.",
    DeletingAccount: "Deleting account...",
    OfferSent: "Offer Sent",
    WaitingForUserResponse: "The user hasn't responded to your offer yet.",
    OfferPending: "Offer Pending",
    ArrivedAtPickup: "📍 You've arrived! The user is nearby for pickup.",
    ArrivedAtDropoff: "📍 You've reached the drop-off location!",
    DriverArrivedAtPickup: "📍 Driver has arrived at pickup location.",
    DriverArrivedAtDropoff: "📍 Driver is at the drop-off location.",
    PendingOfferMessage: "Driver has submitted an offer. Please check the details and send your response.",
    CheckOffer: "Check Offer",
    AcceptRejectReply: "Accept / Reject Reply",
    DriverVerificationDetails: "Driver Verification Details",
    SecurityAndVerification: "Security & Verification",
    VerifiedProfileVehicleDocs: "View verified profile, vehicle & documents",
    VerifiedProfileVehicleDocsDesc: "This driver profile is fully verified for security and parcel safety.",
    AppRegisteredName: "App Registered Name",
    VehicleSetupRegistration: "Vehicle Setup & Registration",
    BankDetailsHolderName: "Bank Details (Check Holder Name)",
    VerificationDocuments: "Verification Documents",
    IDDocumentLabel: "ID Document",
    LicensePhotoLabel: "License Photo",
    RegistrationLabel: "Registration",
  },

  mn: {
    ChangeLanguage: "Хэл солих",
    Logout: "Гарах",
    LogoutConfirmMessage: "Та системээс гарахдаа итгэлтэй байна уу?",
    PhysicalData: "Физик өгөгдөл",
    UsefulTips: "Хэрэгтэй зөвлөмжүүд",
    PaymentHistory: "Төлбөрийн түүх",
    Help: "Тусламж",
    ContactInfo: "Холбоо барих мэдээлэл",
    PushNotifications: "Мэдэгдэл",
    UpdateProfile: "Профайлыг шинэчлэх",
    Version: "Хувилбар",
    Profile: "Профайл",
    Add: "Нэмэх",
    RatingLabel: "Үнэлгээ",
    ReviewsLabel: "Шүүмж",
    // Onboarding
    ShipYourParcel: "Илгээмжээ илгээх",
    ShipAnywhere: "Хаана ч илгээх",
    TrackYourParcel: "Илгээмжээ хянах",
    OnboardingDesc1: "Илгээмж илгээх үйл явцыг саадгүй, стрессгүй мэдрээрэй.",
    OnboardingDesc2: "Манай найдвартай, аюулгүй хүргэлтийн үйлчилгээгээр илгээмжээ хил дамнуулан илгээгээрэй.",
    OnboardingDesc3: "Илгээмжийнхээ бодит байршлыг хүссэн үедээ мэдэж, мэдээлэлтэй байгаарай.",
    Skip: "Алгасах",
    Continue: "Үргэлжлүүлэх",
    // Choose Role
    ChooseRole: "Хэрэглэгчийн үүргээ сонгоно уу",
    User: "Хэрэглэгч",
    Delivery: "Хүргэлт",
    PleaseSelectRole: "Үргэлжлүүлэхийн өмнө үүргээ сонгоно уу.",
    // Profile
    EditProfile: "Профайлыг засах",
    MyOrders: "Миний захиалга",
    PrivacyPolicy: "Нууцлалын бодлого",
    TermsConditions: "Үйлчилгээний нөхцөл",
    // Login
    PhoneQuestion: "Таны утасны дугаар хэд вэ?",
    PhoneSubtitle: "Бид таныг баталгаажуулах код илгээх болно",
    PhoneNumber: "Утасны дугаар",
    SelectCountry: "Улс сонгох",
    SearchCountry: "Улс хайх",
    Cancel: "Цуцлах",
    PleaseEnterPhone: "Утасны дугаараа оруулна уу.",
    PleaseEnterValidPhone: "Зөв утасны дугаар оруулна уу (6-15 оронтой).",
    ContinueWithNumber: "Дугаараар үргэлжлүүлэх",
    ContinueWithGoogle: "Google-ээр үргэлжлүүлэх",
    FullName: "Овог нэр",
    Email: "Имэйл",
    Address: "Хаяг",
    Update: "Шинэчлэх",
    // Status Labels
    StatusPending: "Хүлээгдэж буй",
    StatusAssigned: "Оноогдсон",
    StatusGoingToPickup: "Авахаар явж байна",
    StatusPickedUp: "Авсан",
    StatusOnTheWay: "Замдаа",
    StatusArriving: "Ойртож байна",
    StatusDelivered: "Хүргэгдсэн",
    StatusCompleted: "Дууссан",
    StatusCancelled: "Цуцлагдсан",
    // Orders Screen
    Orders: "Захиалгууд",
    Pending: "Хүлээгдэж буй",
    Complete: "Дууссан",
    Canceled: "Цуцлагдсан",
    NoOrdersFound: "Захиалга олдсонгүй",
    NoOrdersHereYet: "Энд одоогоор захиалга алга.",
    NoOrder: "Идэвхтэй захиалга алга",
    NoOrdersFound1: "Таны тээвэрлэлтийн түүх хоосон байна. Анхны илгээмжийн хүсэлтээ үүсгэж эхэлнэ үү.",
    TrackingID: "Хяналтын ID",
    StepXofY: "{1}-ээс {0}-р алхам дууссан",
    ViewDetails: "Дэлгэрэнгүй үзэх",
    WriteAReview: "Сэтгэгдэл бичих",
    // General
    Search: "Хайх",
    Notifications: "Мэдэгдэл",
    Home: "Нүүр",
    Inbox: "Ирсэн",
    Tracking: "Хяналт",
    From: "Хаанаас",
    To: "Хаашаа",
    DeliveryStatus: "Хүргэлтийн төлөв",
    CreateParcel: "Илгээмж үүсгэх",
    ShippingHistory: "Тээвэрлэлтийн түүх",
    SelectDeliveryAddress: "Хүргэлтийн хаягаа сонгоно уу",
    OfferAccepted: "Санал хүлээн авсан",
    DriverAcceptedOffer: "Жолооч таны саналыг хүлээн авлаа.",
    Order: "Захиалга",
    Carrier: "Тээвэрлэгч",
    OfferPrice: "Санал болгож буй үнэ",
    MessageLabel: "Мессеж",
    PhoneLabel: "Утас",
    Accept: "ЗӨВШӨӨРӨХ",
    CounterOfferLabel: "ЭСРЭГ САНАЛ",
    Chat: "ЧАТ",
    Back: "Буцах",
    OffersForYourAd: "ТАНЫ ЗАРЫН САНАЛУУД",
    OfferInformation: "Саналын мэдээлэл",
    ProposedAmount: "Санал болгож буй дүн",
    NoOffersAvailable: "Одоогоор таны зард санал ирээгүй байна.",
    FindingDriver: "Жолооч хайж байна",
    DriversLabel: "ЖОЛООЧ НАР",
    RadiusLabel: "РАДИУС",
    ScanningArea: "ОРЧНЫГ ШАЛГАЖ БАЙНА",
    CancelSearch: "ХАЙЛТЫГ ЦУЦЛАХ",
    RetryLabel: "ДАХИН ОРОЛДОХ",
    SearchingDrivers: "Боломжтой жолооч хайж байна...",
    ConnectingNetwork: "Сүлжээнд холбогдож байна",
    DriverConfirmed: "Жолооч баталгаажсан • Хүлээн авахаар бэлтгэж байна",
    DriverEnRoute: "Жолооч явж байна • ETA тооцоолж байна",
    ParcelCollected: "Илгээмжийг авсан • Замдаа",
    ParcelDelivered: "Илгээмжийг хүргэж дууссан",
    SearchInboxPlaceholder: "Нэр, хяналтын",
    NoChatsYet: "Одоогоор чат алга",
    NoConversationsSubtitle: "Таны харилцан ярианууд энд харагдах болно",
    ActiveDeliveryConversations: "{0} идэвхтэй хүргэлтийн харилцан яриа",
    NoActiveDeliveryChats: "Идэвхтэй хүргэлтийн чат байхгүй",
    SessionExpired: "Холболтын хугацаа дууслаа. Дахин нэвтэрнэ үү.",
    FailedLoadChats: "Чатуудыг ачаалж чадсангүй. Дахин оролдоно уу.",
    NoMessagesYet: "Мессеж алга",
    Unknown: "Үл мэдэгдэх",
    Today: "Өнөөдөр",
    Yesterday: "Өчигдөр",
    DeliveryAgent: "Хүргэлтийн ажилтан",
    TypeAMessage: "Мессеж бичих...",
    LoadingMessages: "Мессежүүдийг ачаалж байна...",
    NoMessagesYetSayHi: "Одоогоор мессеж алга. Сайн уу гэж хэлээрэй!",
    OrderOpen: "Захиалга нээлттэй",
    ErrorLabel: "Алдаа",
    PhoneNotAvailable: "Утасны дугаар байхгүй байна",
    PhoneCallNotSupported: "Утасны дуудлага хийх боломжгүй байна",
    SomethingWentWrong: "Ямар нэг зүйл буруу боллоо",
    FailedAcceptOffer: "Саналыг хүлээн авч чадсангүй",
    FailedSendCounterOffer: "Эсрэг саналыг илгээж чадсангүй",
    CounterOfferSent: "Эсрэг саналыг амжилттай илгээлээ!",
    OfferAcceptedSuccess: "Саналыг амжилттай хүлээн авлаа!",
    InvalidOfferId: "Буруу саналын ID",
    ThisWeek: "Энэ долоо хоног",
    GeneralNotification: "Ерөнхий мэдэгдэл",
    Sound: "Дуу",
    Vibrate: "Чичиргээ",
    NewTipsAvailable: "Шинэ зөвлөгөө боломжтой",
    EnterVerificationCode: "Баталгаажуулах кодыг оруулна уу",
    SentCodeTo: "Бид таны {0} дугаарт 4 оронтой код илгээсэн",
    DidntReceiveOTP: "Код ирээгүй юу?",
    ResendIn: "Дахин илгээх хугацаа",
    ResendOTPButton: "КОД ДАХИН ИЛГЭЭХ",
    NoContentAvailable: "Агуулга байхгүй байна",
    LoginSuccess: "OTP амжилттай илгээгдлээ!",
    LoginFailed: "Нэвтрэх амжилтгүй боллоо. Дахин оролдоно уу.",
    VerificationSuccess: "Амжилттай нэвтэрлээ!",
    InvalidOTP: "OTP код буруу байна. Дахин оролдоно уу.",
    ResendSuccess: "OTP кодыг дахин амжилттай илгээлээ!",
    ResendFailed: "OTP кодыг дахин илгээхэд алдаа гарлаа. Дахин оролдоно уу.",
    // Delivery Side
    EarningsReports: "Орлого ба тайлан",
    DocumentShow: "Баримт бичиг харах",
    Wallet: "Түрүүвч",
    Support: "Тусламж",
    ShareApp: "Бусдад санал болгох",
    RateDelivery: "Хүргэлтийн тариф",

    TodaysEarnings: "Өнөөдрийн орлого",
    PendingRides: "Хүлээгдэж буй аялал",
    TodaysRides: "Өнөөдрийн аялал",
    WeeklyEarnings: "Долоо хоногийн орлого",
    WeeklyRides: "Долоо хоногийн аялал",
    PickupFrom: "АВАХ ГАЗАР",
    DeliverTo: "ХҮРГЭХ ГАЗАР",
    RouteMap: "Маршрутын зураг",
    DeliverySchedule: "Хүргэлтийн хуваарь",
    PickupDate: "Авах огноо",
    PickupTime: "Авах цаг",
    OfferStatus: "Саналын төлөв",
    Reject: "Татгалзах",
    AcceptDelivery: "Хүргэлтийг зөвшөөрөх",
    RejectDelivery: "Хүргэлтээс татгалзах",
    RejectDeliveryConfirm: "Та энэ хүргэлтээс татгалзахдаа итгэлтэй байна уу?",
    TotalEarnings: "Нийт орлого",
    Activity: "Үйл ажиллагаа",
    OnlineHrs: "Онлайн цаг",
    Trips: "Аялал",
    CashTrip: "Бэлэн мөнгөний аялал",
    HowCanWeHelp: "Бид танд яаж туслах вэ?",
    TypeHere: "Энд бичнэ үү...",
    Submit: "Илгээх",
    AvailableBalance: "Таны боломжтой үлдэгдэл",
    Withdraw: "Зарлага гаргах",
    AddAmount: "Мөнгө нэмэх",
    AddMoney: "Мөнгө нэмэх",
    WithdrawMoney: "Мөнгө гаргах",
    EnterAmount: "Дүн оруулна уу",
    EnterValidAmount: "Зөв дүн оруулна уу",
    MinimumIs: "Хамгийн багадаа",
    MaximumIs: "Хамгийн ихдээ",
    Confirm: "Баталгаажуулах",
    Sun: "НЯМ",
    Mon: "ДАВ",
    Tue: "МЯГ",
    Wed: "ЛХА",
    Thu: "ПҮР",
    Fri: "БАА",
    Sat: "БЯМ",
    SuccessLabel: "Амжилттай",
    DeliveryAcceptedSuccess: "Хүргэлтийг амжилттай зөвшөөрлөө!",
    FailedLoadOrders: "Захиалгын мэдээллийг ачаалж чадсангүй",
    SendOffer: "Санал илгээх",
    StartPickup: "Авч эхлэх",
    MarkAsPickedUp: "Авсан гэж тэмдэглэх",
    StartDelivery: "Хүргэлтийг эхлүүлэх",
    MarkAsDelivered: "Хүргэгдсэн гэж тэмдэглэх",
    OrderCompleted: "Захиалга дууссан",
    OrderCancelled: "Захиалга цуцлагдсан",
    Processing: "Боловсруулж байна...",
    PickupOtpError: "Хэрэглэгчийн өгсөн авах OTP-г оруулна уу",
    DeliveryOtpError: "Хэрэглэгчийн өгсөн хүргэлтийн OTP-г оруулна уу",
    ParcelDetails: "Илгээмжийн дэлгэрэнгүй",
    PickupLocation: "Авах байршил",
    DropLocation: "Хүргэх байршил",
    ParcelInformation: "Илгээмжийн мэдээлэл",
    Price: "Үнэ",
    SenderName: "Илгээгчийн нэр",
    ReceiverName: "Хүлээн авагчийн нэр",
    ReceiverPhone: "Хүлээн авагчийн утас",
    PackageSize: "Багцын хэмжээ",
    ConsignmentType: "Ачааны төрөл",
    ShipmentType: "Тээвэрлэлтийн төрөл",
    MakeOffer: "Санал болгох",
    AmountWithCurrency: "Дүн ₮",
    TypeMessageHere: "Мессежээ энд бичнэ үү...",
    CancelOrderConfirm: "Та энэ захиалгыг цуцлахдаа итгэлтэй байна уу?",
    CreateAccount: "Бүртгэл үүсгэх",
    AlreadyHaveAccount: "Бүртгэлтэй хэрэглэгч",
    EnterFullNameError: "Бүтэн нэрээ оруулна уу.",
    EnterEmailError: "Имэйл хаягаа оруулна уу.",
    ValidEmailError: "Зөв имэйл хаяг оруулна уу.",
    EnterAddressError: "Хаягаа оруулна уу.",
    UploadProfileImageError: "Профайл зургаа оруулна уу.",
    UploadDocuments: "Баримт бичиг байршуулах",
    UploadIdDocument: "Иргэний үнэмлэх байршуулах",
    UploadDrivingLicense: "Жолооны үнэмлэх байршуулах",
    UploadVehiclePapers: "Автомашины бичиг баримт байршуулах",
    UploadDocumentsError: "Шаардлагатай бүх баримт бичгийг байршуулна уу.",
    DrivingLicenseNumber: "Жолооны үнэмлэхний дугаар",
    BankName: "Банкны нэр",
    AccountNumber: "Дансны дугаар",
    IFSCCode: "IFSC код",
    EnterLicenseNumberError: "Жолооны үнэмлэхний дугаараа оруулна уу.",
    EnterPhoneNumberError: "Утасны дугаараа оруулна уу.",
    EnterBankNameError: "Банкны нэрээ оруулна уу.",
    EnterAccountNumberError: "Дансны дугаараа оруулна уу.",
    EnterIFSCCodeError: "Банкны IFSC кодыг оруулна уу.",
    BankSetup: "Банкны тохиргоо",
    BankSetupSubtitle: "Хүргэлтийн төлбөр хүлээн авах банкны дансаа оруулна уу.",
    BankSecureNote: "Аюулгүй мэдээлэл",
    PayoutReady: "Төлбөр хүлээн авах дансны мэдээлэл",
    EnterBankName: "Банкны нэр оруулна уу",
    EnterAccountNumber: "Дансны дугаар оруулна уу",
    EnterIFSCCode: "IFSC код оруулна уу",
    SaveAndFinish: "Хадгалах ба Дуусгах",
    VehicleSetup: "Тээврийн хэрэгслийн тохиргоо",
    VehicleSetupSubtitle: "Баталгаажуулалтаа үргэлжлүүлэхийн тулд тээврийн хэрэгслийн мэдээлэл болон гэрчилгээгээ оруулна уу.",
    SelectVehicleType: "Тээврийн хэрэгслийн төрөл сонгох",
    EnterVehicleNumber: "Улсын дугаар оруулна уу",
    UploadVehicleRegistration: "Тээврийн хэрэгслийн гэрчилгээ байршуулах",
    VehicleUploadHint: "Камер эсвэл галерейн зураг ашиглаж болно",
    Change: "Солих",
    TakeClearPhoto: "Тод зураг авна уу",
    ChooseFromPhone: "Утаснаасаа сонгох",
    RemoveSelectedDocument: "Сонгосон баримтыг устгах",
    SelectVehicleTypeError: "Тээврийн хэрэгслийн төрлийг сонгоно уу.",
    EnterVehicleNumberError: "Тээврийн хэрэгслийн дугаарыг оруулна уу.",
    UploadVehicleRegistrationError: "Тээврийн хэрэгслийн гэрчилгээг байршуулна уу.",
    SaveAndContinue: "Хадгалах ба үргэлжлүүлэх",
    Car: "Суудлын тэрэг",
    Bike: "Мотоцикл",
    Van: "Микро автобус",
    Truck: "Ачааны машин",
    Confirmation: "Баталгаажуулалт",
    Yes: "Тийм",
    No: "Үгүй",
    Message: "Мессеж",
    RateYourDelivery: "Хүргэлтийг үнэлэх",
    ViewOffer: "Санал харах",
    TrackDetail: "Дэлгэрэнгүй хянах",
    TrackingPackage: "Илгээмж хянах",
    Done: "Дууссан",
    RatingSuccess: "Үнэлгээ өгсөнд баярлалаа!",
    RatingPoor: "Муу",
    RatingFair: "Дунд",
    RatingGood: "Сайн",
    RatingGreat: "Маш сайн",
    RatingExcellent: "Гайхалтай",
    HowWasExperience: "Таны сэтгэгдэл ямар байсан бэ?",
    ShareExperiencePlaceholder: "Өөрийн сэтгэгдлээ хуваалцана уу (заавал биш)",
    ParcelUpdated: "Илгээмж шинэчлэгдсэн",
    OrderNumber: "Захиалгын дугаар: ",
    OK: "ОК",
    PickupAndDrop: "Авах ба Хүргэх",
    AddPickupLocation: "Авах байршил нэмэх",
    AddDropLocation: "Хүргэх байршил нэмэх",
    ShipmentSenderDetails: "Тээвэрлэлт ба Илгээгчийн мэдээлэл",
    SenderMobileNumber: "Илгээгчийн утасны дугаар",
    ReceiverDetails: "Хүлээн авагчийн мэдээлэл",
    ReceiverMobileNumber: "Хүлээн авагчийн утасны дугаар",
    ExtraMessage: "Нэмэлт мессеж",
    AddParcelImage: "Илгээмжийн зураг нэмэх",
    SendRequest: "Хүсэлт илгээх",
    Standard: "Стандарт",
    Express: "Экспресс",
    Normal: "Ердийн",
    Fast: "Хурдан",
    PickupLocationRequired: "Авах байршил шаардлагатай",
    DropLocationRequired: "Хүргэх байршил шаардлагатай",
    PickupRequestSuccess: "Авах хүсэлтийг амжилттай илгээлээ!",
    FillRequiredFieldsError: "Шаардлагатай бүх талбарыг зөв бөглөнө үү",
    AssigningDriver: "Жолооч оноож байна...",
    OTP: "OTP",
    Size: "Хэмжээ",
    Type: "Төрөл",
    Service: "Үйлчилгээ",
    Pickup: "Авах",
    Drop: "Хүргэх",
    Calculating: "Тооцоолж байна...",
    DeliveryType: "Хүргэлтийн төрөл",
    Slide: "Гулсуулах",
    AddAddress: "Хаяг нэмэх",
    HomeType: "Гэр",
    OfficeType: "Оффис",
    Today: "Өнөөдөр",
    Yesterday: "Өчигдөр",
    OfferAcceptedSuccess: "Саналыг амжилттай хүлээн авлаа!",
    OfferAcceptFailed: "Саналыг хүлээн авахад алдаа гарлаа",
    SomethingWentWrong: "Ямар нэг зүйл буруу боллоо",
    CounterOfferSent: "Сөрөг саналыг амжилттай илгээлээ!",
    CounterOfferFailed: "Сөрөг саналыг илгээхэд алдаа гарлаа",
    LoadingMessages: "Мессежийг ачаалж байна...",
    NoMessagesYetSayHi: "Мессеж алга. Сайн уу гэж хэлээрэй!",
    TypeAMessage: "Мессеж бичих...",
    InvalidOfferID: "Буруу саналын ID",
    DeliveryAgent: "Хүргэлтийн агент",
    OrderOpen: "Захиалга нээлттэй",
    Error: "Алдаа",
    PhoneNotAvailable: "Утасны дугаар байхгүй",
    PhoneCallNotSupported: "Утасны дуудлага хийх боломжгүй",
    SelectLanguage: "Хэл сонгох",
    // Document Show
    MyDocuments: "Миний баримт бичиг",
    DocumentShowSubtitle: "Бичиг баримт, тээврийн хэрэгсэл болон төлбөрийн мэдээллээ нэг дор шалгана уу.",
    DocumentUploaded: "Баримт бичиг байршуулсан",
    UploadIdentityDocuments: "Бичиг баримт байршуулах",
    SetUpVehicleDetails: "Тээврийн хэрэгслийн мэдээлэл оруулах",
    SetUpBankDetails: "Банкны мэдээлэл оруулах",
    Identity: "Хувь хүн",
    Vehicle: "Тээврийн хэрэгсэл",
    Banking: "Банк",
    Identification: "Бичиг баримт",
    DrivingLicense: "Жолооны үнэмлэх",
    IDDocument: "Иргэний үнэмлэх",
    VehiclePapers: "Автомашины бичиг баримт",
    TapToEnlarge: "Томруулж үзэх",
    VehicleInformation: "Тээврийн хэрэгслийн мэдээлэл",
    VehicleType: "Тээврийн хэрэгслийн төрөл",
    VehicleNumber: "Улсын дугаар",
    Model: "Загвар",
    Color: "Өнгө",
    RegistrationPaper: "Гэрчилгээ",
    YourBank: "Таны банк",
    AccountNumber: "Дансны дугаар",
    AccountHolder: "Данс эзэмшигч",
    IFSCCode: "IFSC код",
    Verified: "Баталгаажсан",
    InReview: "Хянагдаж байгаа",
    Pending: "Хүлээгдэж буй",
    FetchingDetails: "Мэдээлэл татаж байна...",
    NoDataFound: "Мэдээлэл олдсонгүй",
    InfoWillAppearHere: "Мэдээллийг боловсруулж дууссаны дараа энд харагдах болно.",
    TypeAMessagePlaceholder: "Мессеж бичих...",
    // Location & Search
    Locating: "Байршил тогтоож байна...",
    UnknownLocation: "Үл мэдэгдэх байршил",
    PermissionDenied: "Байршлын зөвшөөрөл татгалзсан",
    UnableGetLocation: "Байршлыг тогтоох боломжгүй",
    SearchPickupArea: "Авах бүсийг хайх",
    SetPickup: "Авах цэгийг тохируулах",
    ConfirmLocation: "Байршлыг баталгаажуулах",
    SearchAddress: "Хаяг хайх",
    EnterAddressPlaceholder: "Хаягаа оруулна уу...",
    SearchingNearby: "Ойр орчмыг хайж байна...",
    NoResultsRegion: "Энэ бүсэд илэрц олдсонгүй",
    // Image Picker
    ChooseOption: "Сонголт хийнэ үү",
    SelectGallery: "Галерейгаас сонгох",
    TakePhoto: "Зураг авах",
    DocumentLabel: "Бичиг баримт",
    ParcelLabel: "Илгээмж",
    SmallSize: "1 кг",
    MediumSize: "3кг - 10кг",
    LargeSize: "10кг+",
    NoInternetConnection: "Интернет холболтгүй байна! Холболтоо шалгана уу.",
    BackOnline: "Онлайн боллоо",
    CheckWifiData: "Та Wi-Fi эсвэл дата холболтоо шалгана уу",
    Enter4DigitOTP: "4 оронтой OTP кодоо оруулна уу",
    InvalidServerResponse: "Серверийн хариу алдаатай",
    NetworkErrorTryAgain: "Сүлжээний алдаа. Дахин оролдоно уу.",
    SomethingWentWrong: "Алдаа гарлаа. Дахин оролдоно уу.",
    ValueNotFound: "Утга олдсонгүй",
    TokenNotFound: "Токен олдсонгүй",
    EnterPickupOTP: "Хэрэглэгчийн хуваалцсан авах цэгийн OTP кодоо оруулна уу",
    EnterAmount: "Дүн оруулна уу",
    EnterMessage: "Мессеж оруулна уу",
    ErrorPickingImage: "Зураг сонгоход алдаа гарлаа",
    ErrorPickingDocument: "Баримт бичиг сонгоход алдаа гарлаа",
    SelectDocument: "Баримт бичиг сонгох",
    Confirmation: "Баталгаажуулт",
    AreYouSureCancel: "Та цуцлахдаа итгэлтэй байна уу?",
    OrderCompleted: "Захиалга дууссан",
    OrderCancelled: "Захиалга цуцлагдсан",
    Processing: "Боловсруулж байна...",
    EnterPickupOTPShared: "Хэрэглэгчийн хуваалцсан авах цэгийн OTP кодыг оруулна уу",
    EnterDeliveryOTPShared: "Хэрэглэгчийн хуваалцсан хүргэлтийн OTP кодыг оруулна уу",
    CancelOrder: "Захиалга цуцлах",
    NextStep: "Дараагийн алхам: {0}",
    FailedUpdateStatus: "Төлөв шинэчлэхэд алдаа гарлаа",
    EnterOTP: "OTP кодыг оруулна уу",
    ConnectionErrorRetrying: "Холболтын алдаа. Дахин оролдож байна...",
    ConnectionFailedTryAgain: "Холболт амжилтгүй боллоо. Дахин оролдоно уу.",
    FailedConnectCheckInternet: "Холбогдож чадсангүй. Интернэтээ шалгана уу.",
    AuthTokenNotFound: "Баталгаажуулах токен олдсонгүй",
    ParcelIDNotFound: "Илгээмжийн ID олдсонгүй",
    NoPartnerAccepted: "Жолооч олдсонгүй",
    NoPartnerAcceptedDesc: "30 секундын дотор хүргэлтийн түнш зөвшөөрсөнгүй. Дахин хайх эсвэл буцах товчийг дарна уу.",
    PleaseWaitFindingPartner: "Бид хамгийн ойрын түншийг хайж байх хооронд хүлээнэ үү",
    CurrentLocation: "Одоогийн байршил",
    XSecLeft: "{0} сек үлдлээ",
    LanguageSelectionTitle: "Бидэнтэй хамт аялалаа эхлүүлэхийн тулд хэлээ сонгоно уу.",
    LanguageSelectionUpdate: "Аппликешны хэлний тохиргоогоо шинэчилнэ үү.",
    StartPickup: "Ачилт эхлэх",
    MarkPickedUp: "Ачуулсан гэж тэмдэглэх",
    StartDelivery: "Хүргэлт эхлэх",
    MarkDelivered: "Хүргэсэн гэж тэмдэглэх",
    StatusUpdatedTo: "Амжилттай, Төлөв {0} болж өөрчлөгдлөө",
    CounterOfferReceived: "Эсрэг санал ирлээ",
    NewDeliveryRequest: "Хүргэлтийн шинэ хүсэлт",
    CounterOfferMessage: "Хэрэглэгч эсрэг санал ирүүлсэн байна. Үзэж, хариу өгөхийн тулд товшино уу.",
    UserOfferedNewPrice: "Хэрэглэгч шинэ үнэ санал болголоо",
    ReviewAcceptDeliveryOffer: "Энэ хүргэлтийн саналыг баталгаажуулахын тулд шалгаад зөвшөөрнө үү.",
    NewDeliveryRequestMessage: "Ойролцоо илгээмж авах газар байна. Дэлгэрэнгүйг үзэж, саналаа илгээхийн тулд доор товшино уу.",
    Later: "Дараа",
    UpdateAvailableTitle: "Шинэ хувилбар гарсан байна",
    UpdateAvailableMessage: "Daina аппын шинэ хувилбар бэлэн боллоо. Шинэ боломжууд болон засваруудыг авахын тулд апп аа шинэчилнэ үү.",
    UpdateNow: "Одоо шинэчлэх",
    VersionUpdateText: "Одоогийн {0} - Шинэ {1}",
    Rating: "Үнэлгээ өгсөнд баярлалаа!",
    OrderCancelled: "Захиалгыг амжилттай цуцалсан",
    ViewOrder: "Захиалга харах",
    NoNotifications: "Мэдэгдэл олдсонгүй",
    FileTooLarge: "Файлын хэмжээ хэтэрхий том байна. Жижиг файл сонгоно уу.",
    Camera: "Камер",
    PDF: "PDF",
    Remove: "Хасах",
    ChooseOption: "Сонголт сонгох",
    SlideToGoOnline: "Онлайн болохын тулд гүйлгэ",
    SlideToGoOffline: "Оффлайн болохын тулд гүйлгэ",
    VerificationTitle: "Бүртгэл баталгаажуулалт",
    VerificationSubtitle: "Таны бичиг баримтыг манай админ баг хянаж байна.",
    VerificationDescription: "Энэхүү үйл явц нь ихэвчлэн 24-48 цаг үргэлжилдэг. Таны бүртгэл идэвхжсэн даруйд бид танд мэдэгдэх болно. Түр хүлээнэ үү!",
    VerificationPending: "Баталгаажуулалт хүлээгдэж байна",
    InProgress: "Явц дунд",
    PendingApproval: "ЗӨВШӨӨРӨЛ ХҮЛЭЭЖ БАЙНА",
    VerificationPendingDesc: "Таны хүсэлтийг хянаж дуусаж байна. Бэлэн болох үед бид танд мэдэгдэх болно.",
    ReviewProgress: "Хяналтын явц",
    DocumentsUploaded: "Бичиг баримт илгээгдсэн",
    DocumentsUploadedDesc: "Иргэний үнэмлэх, жолооны үнэмлэх болон тээврийн хэрэгслийн бичиг баримт",
    AdminVerification: "Админ хяналт",
    AdminVerificationDesc: "Илгээсэн бичиг баримтыг гараар шалгаж байна",
    BackgroundCheck: "Арын шалгалт",
    BackgroundCheckDesc: "Аюулгүй байдал, нийцлийн шалгалт",
    ReadyForOrders: "Захиалга авахад бэлэн",
    ReadyForOrdersDesc: "Илгээмж хүргэх хүсэлтүүд авах боломжтой",
    DidYouKnow: "Та мэдэх үү?",
    VerificationTip: "Бүрэн гүйцэд профайлыг 3 дахин хурдан баталгаажуулдаг. Зурагнууд тань тод, уншигдахуйц байгаа эсэхийг шалгаарай.",
    RefreshStatus: "Төлөв шинэчлэх",
    DeleteAccount: "Бүртгэл устгах",
    DeleteAccountConfirmTitle: "Бүртгэл устгах",
    DeleteAccountConfirmMessage: "Та бүртгэлээ устгахдаа итгэлтэй байна уу? Энэ үйлдлийг буцаах боломжгүй бөгөөд таны бүх мэдээлэл бүрмөсөн устах болно.",
    DeletingAccount: "Бүртгэл устгаж байна...",
    OfferSent: "Санал илгээсэн",
    WaitingForUserResponse: "Хэрэглэгч таны саналд хараахан хариу өгөөгүй байна.",
    OfferPending: "Санал хүлээгдэж байна",
    ArrivedAtPickup: "📍 Та ирлээ! Хэрэглэгч авах цэгт ойрхон байна.",
    ArrivedAtDropoff: "📍 Та хүргэх цэгт ирлээ!",
    DriverArrivedAtPickup: "📍 Жолооч авах цэг дээр ирлээ.",
    DriverArrivedAtDropoff: "📍 Жолооч хүргэх цэг дээр ирлээ.",
    PendingOfferMessage: "Жолооч санал ирүүлсэн байна. Дэлгэрэнгүйг шалгаад хариугаа илгээнэ үү.",
    CheckOffer: "Санал шалгах",
    AcceptRejectReply: "Зөвшөөрөх / Татгалзах хариу",
    DriverVerificationDetails: "Жолоочийн баталгаажуулалтын мэдээлэл",
    SecurityAndVerification: "Аюулгүй байдал ба баталгаажуулалт",
    VerifiedProfileVehicleDocs: "Баталгаажсан профайл, тээврийн хэрэгсэл, баримт бичгийг үзэх",
    VerifiedProfileVehicleDocsDesc: "Энэхүү жолоочийн профайл нь аюулгүй байдал болон илгээмжийн найдвартай байдлын хувьд бүрэн баталгаажсан болно.",
    AppRegisteredName: "Аппликэйшнд бүртгэлтэй нэр",
    VehicleSetupRegistration: "Тээврийн хэрэгслийн тохиргоо ба бүртгэл",
    BankDetailsHolderName: "Банкны мэдээлэл (Данс эзэмшигчийн нэр)",
    VerificationDocuments: "Баталгаажуулалтын баримт бичиг",
    IDDocumentLabel: "Иргэний үнэмлэх",
    LicensePhotoLabel: "Жолооны үнэмлэхний зураг",
    RegistrationLabel: "Тээврийн хэрэгслийн гэрчилгээ",
    Account: "Бүртгэлийн тохиргоо",
    Support: "Дэмжлэг ба хууль эрх зүй",
    Locationu: "Байршил боломжгүй",
    CurrentLocation: "Одоогийн байршил",

    Messages: "Мессежүүд",
    Reply: "Хариулах",
    ViewAll: "Бүгдийг харах"


  },
});

export default strings;
