import { Dimensions, Platform, StyleSheet } from 'react-native';
import font from '../../../theme/font';

const { width } = Dimensions.get('window');
const YELLOW = '#FFCC00';
const DARK = '#111827';
const GRAY_BG = '#F3F4F6';
const LIGHT_TEXT = '#8E8E93';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 50,
  },
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: YELLOW,
    borderRadius: 24,
    padding: 18,
    marginBottom: 18,
  },
  heroIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  heroTextWrap: {
    flex: 1,
  },
  heroTitle: {
    color: DARK,
    fontSize: 21,
    fontFamily: font.MonolithRegular,
  },
  heroSubtitle: {
    color: '#3F3F46',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 7,
    fontFamily: font.MonolithRegular,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#EEF2F6',
    padding: 6,
    borderRadius: 18,
    marginBottom: 24,
  },
  tabButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    borderRadius: 14,
    justifyContent: "center",
    flexDirection: 'row',
    gap: 6,
  },
  activeTabButton: {
    backgroundColor: YELLOW,
    ...Platform.select({
      ios: {
        shadowColor: YELLOW,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
      },

    }),
  },
  tabText: {
    fontSize: 12,
    fontFamily: font.MonolithRegular,
    color: '#64748B',
  },
  activeTabText: {
    color: DARK,
    fontFamily: font.MonolithRegular,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: font.MonolithRegular,
    color: DARK,
    marginBottom: 16,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    marginBottom: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EEF0F3",
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 15,
      },

    }),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  titleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconContainer: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#FFF7CC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  cardTitleBlock: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: font.MonolithRegular,
    color: DARK,
  },
  cardSubtitle: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 4,
    fontFamily: font.MonolithRegular,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    marginLeft: 8,
  },
  statusText: {
    fontSize: 10,
    fontFamily: font.MonolithRegular,
  },
  verifiedBadge: { backgroundColor: 'rgba(52, 199, 89, 0.1)' },
  reviewBadge: { backgroundColor: 'rgba(0, 122, 255, 0.1)' },
  pendingBadge: { backgroundColor: 'rgba(255, 149, 0, 0.1)' },
  verifiedText: {
    color: '#34C759', fontFamily: font.MonolithRegular,
  },
  reviewText: {
    color: '#007AFF', fontFamily: font.MonolithRegular,
  },
  pendingText: {
    color: '#FF9500', fontFamily: font.MonolithRegular,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 14,
    marginBottom: 8,
  },
  infoItem: {
    width: '50%',
    marginBottom: 10,
  },
  infoLabel: {
    fontSize: 12,
    color: LIGHT_TEXT,
    marginBottom: 4,
    fontFamily: font.MonolithRegular,
  },
  infoValue: {
    fontSize: 15,
    color: DARK,
    fontFamily: font.MonolithRegular,
  },
  docImageWrapper: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: GRAY_BG,
    marginTop: 8,
  },
  image: {
    width: '100%',
    height: 190,
    backgroundColor: GRAY_BG,
  },
  imageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(17,24,39,0.76)',
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  overlayText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: font.MonolithRegular,
    marginLeft: 7,
  },
  vehicleCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 14,
    borderWidth: 1,
    borderColor: '#EEF0F3',
    marginBottom: 18,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.06,
        shadowRadius: 16,
      },

    }),
  },
  vehicleHero: {
    backgroundColor: YELLOW,
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
  },
  vehicleHeroTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  vehicleIconLarge: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  vehicleHeroLabel: {
    color: '#3F3F46',
    fontSize: 12,
    fontFamily: font.MonolithRegular,
  },
  vehiclePlate: {
    color: DARK,
    fontSize: 24,
    marginTop: 8,
    fontFamily: font.MonolithRegular,
  },
  vehicleTypeText: {
    color: DARK,
    fontSize: 14,
    marginTop: 6,
    fontFamily: font.MonolithRegular,
  },
  vehicleDetailGrid: {
    gap: 10,
    marginBottom: 14,
  },
  vehicleDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  vehicleDetailIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: '#FFF7CC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  vehicleDetailTextWrap: {
    flex: 1,
  },
  vehicleDocumentPreview: {
    height: 190,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: GRAY_BG,
  },
  vehicleDocumentImage: {
    width: '100%',
    height: '100%',
    backgroundColor: GRAY_BG,
  },
  vehicleDocOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 54,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(17,24,39,0.78)',
  },
  vehicleDocTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  vehicleZoomPill: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: YELLOW,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  bankCard: {
    backgroundColor: YELLOW,
    borderRadius: 24,
    padding: 22,
    minHeight: 210,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  bankHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bankName: {
    color: DARK,
    fontSize: 19,
    fontFamily: font.MonolithRegular,
    marginTop: 5,
  },
  bankChip: {
    width: 52,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  accountNumber: {
    color: DARK,
    fontSize: 22,
    letterSpacing: 3,
    marginVertical: 28,
    textAlign: 'left',
    opacity: 0.9,
  },
  bankFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  bankLabel: {
    color: '#3F3F46',
    fontSize: 10,
    textTransform: 'uppercase',
    marginBottom: 6,
    fontFamily: font.MonolithRegular,
    letterSpacing: 1,
  },
  bankValue: {
    color: DARK,
    fontSize: 14,
    fontFamily: font.MonolithRegular,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#EEF0F3',
  },
  emptyIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 24,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 19,
    fontFamily: font.MonolithRegular,
    color: DARK,
    marginTop: 18,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 22,
    fontFamily: font.MonolithRegular,
  },
  emptyButton: {
    backgroundColor: YELLOW,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 18,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  emptyButtonText: {
    color: DARK,
    fontSize: 14,
    fontFamily: font.MonolithRegular,
    textAlign: "center",
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: {
    marginTop: 16,
    color: '#64748B',
    fontFamily: font.MonolithRegular,
    fontSize: 15,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingHorizontal: 24,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    flex: 1,
    width: width,
  },
});
