export default {
    appLogo: require('./images/logo.png'),
    appLogo1: require('./images/logo.png'),
    bag: require('./images/bag.png'),
    fram: require('./images/fram.png'),
    Mobile: require('./images/Mobile.png'),
    ordePracle: require('./images/ordePracle.png'),
    // phonLogoapp: require('./images/Mobile.png'),
    phonLogoapp: require('./images/phonLogoapp.png'),
    dpuser: require('./images/dpuser.png'),
    Editpen: require('./images/Editpen.png'),
    sp1: require('./images/sp1.png'),
    Messagesend: require('./images/Messagesend.png'),
    eoditphots: require('./images/eoditphots.png'),
    bubleYeelow: require('./images/bubleYeelow.png'),
    lock: require('./images/lock.png'),
    Calls: require('./images/Calls.png'),
    hide: require('./images/hide.png'),
    messtrcker: require('./images/messtrcker.png'),
    locationpin: require('./images/locationpin.png'),
    mess: require('./images/mess.png'),
    go: require('./images/go.png'),
    search1: require('./images/search1.png'),
    pin: require('./images/pin.png'),
    Phone1: require('./images/Phone1.png'),
    Iconreceiv: require('./images/Iconreceiv.png'),
    helpPrva: require('./images/helpPrva.png'),
    IconRed: require('./images/IconRed.png'),
    Location: require('./images/Location.png'),
    voies: require('./images/voies.png'),
    profiel: require('./images/profiel.png'),
    rightaArrow: require('./images/rightaArrow.png'),
    earing: require('./images/earing.png'),
    Addressicone: require('./images/Addressicone.png'),
    edit1: require('./images/edit1.png'),
    sp2: require('./images/sp2.png'),
    Closed: require('./images/Closed.png'),
    sp3: require('./images/sp3.png'),
    Next: require('./images/Next.png'),
    Calblack: require('./images/Calblack.png'),
    icons: require('./images/icons1.png'),
    Vector: require('./images/Vector.png'),
    Notification: require('./images/Notification.png'),
    document: require('./images/document.png'),
    MessageBlack: require('./images/MessageBlack.png'),
    trck: require('./images/trck.png'),
    Dots: require('./images/Dots.png'),
    arrowqdown: require('./images/arrowqdown.png'),
    cars: require('./images/cars.png'),
    more_vert: require('./images/more_vert.png'),
    Rectangle: require('./images/Rectangle.png'),
    tracking: require('./images/tracking.png'),

    black: require('./images/black.png'),
    location1: require('./images/location1.png'),
    caricon: require('./images/caricon.jpg'),
    // group: require('./images/goup2.png'),
    group: require('./images/group.png'),
    right: require('./images/arrowRight.png'),
    Icon: require('./images/Icon.png'),
    MohronFag: require('./images/MohronFag.png'),
    caricon2: require('./images/caricon.png'),
    prfile: require('./images/prfile.png'),
    back: require('./images/back.png'),
    arrowDown: require('./images/arrowDown.png'),
    logout: require('./images/logout.png'),
    Filter: require('./images/Filter.png'),
    dounArroww: require('./images/dounArroww.png'),
    aboutus: require('./images/aboutus.png'),
    BackLeft: require('./images/BackLeft.png'),
    OrderPlaced: require('./images/OrderPlaced.png'),
    userLogo: require('./images/userLogo.png'),
    deliver: require('./images/Deliver.png'),




}; 